install.packages("devtools")
library(devtools)

source("https://bioconductor.org/biocLite.R")
biocLite("Biobase")
biocLite("limma")
biocLite("MSnbase")
biocLite("preprocessCore")
biocLite("vsn")
install.packages("devtools")
library(devtools)
source("https://bioconductor.org/biocLite.R")
biocLite()
devtools::install_github("statOmics/MSqRob@MSqRob0.7.5")
library(MSqRob)
install.packages("lme4",dependencies = T)
install.packages("htmltools",dependencies = T)
install.packages("httpuv",dependencies = T)
install.packages("xtable",dependencies = T)
install.packages("DT",dependencies = T)
install.packages("shinyjs",dependencies = T)

devtools::install_github("ludgergoeminne/MSqRob")
library(MSqRob)

shiny::runApp(system.file("App-MSqRob", package="MSqRob"))
shiny::runApp(system.file("App-MSqRob", package="MSqRob"))
